-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 21:06:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Unigrand
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Unigrand
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Unigrand` DEFAULT CHARACTER SET utf8 ;
USE `Unigrand` ;

-- -----------------------------------------------------
-- Table `Unigrand`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Professor` (
  `mat_prof` BIGINT(0) NOT NULL AUTO_INCREMENT,
  `matricula` BIGINT(0) NOT NULL,
  `nom_prof` VARCHAR(45) NOT NULL,
  `endereço` BIGINT(0) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mat_prof`),
  UNIQUE INDEX `mat_prof_UNIQUE` (`mat_prof` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Cursos` (
  `cod_curso` BIGINT(0) NOT NULL AUTO_INCREMENT,
  `nom_curso` VARCHAR(45) NOT NULL,
  `tot_cred` BIGINT(0) NOT NULL,
  `Professor_mat_prof` BIGINT(0) NOT NULL,
  PRIMARY KEY (`cod_curso`, `Professor_mat_prof`),
  UNIQUE INDEX `cod_curso_UNIQUE` (`cod_curso` ASC) VISIBLE,
  UNIQUE INDEX `nom_curso_UNIQUE` (`nom_curso` ASC) VISIBLE,
  INDEX `fk_Cursos_Professor1_idx` (`Professor_mat_prof` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_Professor1`
    FOREIGN KEY (`Professor_mat_prof`)
    REFERENCES `Unigrand`.`Professor` (`mat_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Alunos` (
  `mat_alu` BIGINT(0) NOT NULL AUTO_INCREMENT,
  `nom_alu` VARCHAR(45) NOT NULL,
  `tot_cred` BIGINT(0) NOT NULL,
  `dat_nasc` DATE NOT NULL,
  `mgp` BIGINT(0) NOT NULL,
  `cod_curso` BIGINT(0) NOT NULL,
  PRIMARY KEY (`mat_alu`, `cod_curso`),
  UNIQUE INDEX `mat_alu_UNIQUE` (`mat_alu` ASC) VISIBLE,
  INDEX `fk_Alunos_Cursos_idx` (`cod_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_Cursos`
    FOREIGN KEY (`cod_curso`)
    REFERENCES `Unigrand`.`Cursos` (`cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Matricula` (
  `ano` SMALLINT(4) NOT NULL,
  `semestre` SMALLINT(1) NOT NULL,
  `mat_alu` BIGINT(0) NOT NULL,
  `cod_curso` BIGINT(0) NOT NULL,
  `nota_01` FLOAT(2,2) NOT NULL,
  `nota_02` FLOAT(2,2) NOT NULL,
  `nota_03` FLOAT(2,2) NOT NULL,
  `faltas_01` SMALLINT(2) NOT NULL,
  `faltas_02` SMALLINT(2) NOT NULL,
  `faltas_03` SMALLINT(2) NOT NULL,
  PRIMARY KEY (`ano`, `semestre`, `mat_alu`, `cod_curso`),
  INDEX `fk_Matricula_Alunos1_idx` (`mat_alu` ASC, `cod_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Alunos1`
    FOREIGN KEY (`mat_alu` , `cod_curso`)
    REFERENCES `Unigrand`.`Alunos` (`mat_alu` , `cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Disciplina` (
  `cod_disc` BIGINT(0) NOT NULL AUTO_INCREMENT,
  `nom_disc` VARCHAR(45) NOT NULL,
  `creditos` SMALLINT(3) NOT NULL,
  `tipo_disc` SMALLINT(1) NOT NULL,
  `hrs_obrig` SMALLINT(3) NOT NULL,
  `limite_faltas` SMALLINT(2) NOT NULL,
  `ano` SMALLINT(4) NOT NULL,
  `semestre` SMALLINT(1) NOT NULL,
  `mat_alu` BIGINT(0) NOT NULL,
  `cod_curso` BIGINT(0) NOT NULL,
  PRIMARY KEY (`cod_disc`, `ano`, `semestre`, `mat_alu`, `cod_curso`),
  UNIQUE INDEX `cod_disc_UNIQUE` (`cod_disc` ASC) VISIBLE,
  INDEX `fk_Disciplina_Matricula1_idx` (`ano` ASC, `semestre` ASC, `mat_alu` ASC, `cod_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Disciplina_Matricula1`
    FOREIGN KEY (`ano` , `semestre` , `mat_alu` , `cod_curso`)
    REFERENCES `Unigrand`.`Matricula` (`ano` , `semestre` , `mat_alu` , `cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Matriz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Matriz` (
  `cod_curso` BIGINT(0) NOT NULL,
  `mat_prof` BIGINT(0) NOT NULL,
  `cod_disc` BIGINT(0) NOT NULL,
  `periodo` SMALLINT(1) NOT NULL,
  PRIMARY KEY (`cod_curso`, `mat_prof`, `cod_disc`),
  INDEX `fk_Cursos_has_Disciplina_Disciplina1_idx` (`cod_disc` ASC) VISIBLE,
  INDEX `fk_Cursos_has_Disciplina_Cursos1_idx` (`cod_curso` ASC, `mat_prof` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_has_Disciplina_Cursos1`
    FOREIGN KEY (`cod_curso` , `mat_prof`)
    REFERENCES `Unigrand`.`Cursos` (`cod_curso` , `Professor_mat_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Disciplina_Disciplina1`
    FOREIGN KEY (`cod_disc`)
    REFERENCES `Unigrand`.`Disciplina` (`cod_disc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Turma` (
  `cod_disc` BIGINT(0) NOT NULL,
  `mat_prof` BIGINT(0) NOT NULL,
  `vagas` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`cod_disc`, `mat_prof`),
  INDEX `fk_table1_Professor1_idx` (`mat_prof` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Disciplina1`
    FOREIGN KEY (`cod_disc`)
    REFERENCES `Unigrand`.`Disciplina` (`cod_disc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Professor1`
    FOREIGN KEY (`mat_prof`)
    REFERENCES `Unigrand`.`Professor` (`mat_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Periodo_letivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Periodo_letivo` (
  `ano` SMALLINT(4) NOT NULL,
  `semestre` SMALLINT(1) NOT NULL,
  `mat_alu` BIGINT(0) NOT NULL,
  `cod_curso` BIGINT(0) NOT NULL,
  `cod_disc` BIGINT(0) NOT NULL,
  `mat_prof` BIGINT(0) NOT NULL,
  `dat_inicial` DATE NOT NULL,
  `dat_final` DATE NOT NULL,
  PRIMARY KEY (`ano`, `semestre`, `mat_alu`, `cod_curso`, `cod_disc`, `mat_prof`),
  INDEX `fk_Matricula_has_Turma_Turma1_idx` (`cod_disc` ASC, `mat_prof` ASC) VISIBLE,
  INDEX `fk_Matricula_has_Turma_Matricula1_idx` (`ano` ASC, `semestre` ASC, `mat_alu` ASC, `cod_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_has_Turma_Matricula1`
    FOREIGN KEY (`ano` , `semestre` , `mat_alu` , `cod_curso`)
    REFERENCES `Unigrand`.`Matricula` (`ano` , `semestre` , `mat_alu` , `cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_has_Turma_Turma1`
    FOREIGN KEY (`cod_disc` , `mat_prof`)
    REFERENCES `Unigrand`.`Turma` (`cod_disc` , `mat_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unigrand`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Unigrand`.`Historico` (
  `situação` CHAR(2) NULL,
  `medias` FLOAT(2,2) NULL,
  `faltas` SMALLINT(2) NULL,
  `mat_alu` BIGINT(0) NOT NULL,
  `cod_curso` BIGINT(0) NOT NULL,
  `ano` SMALLINT(4) NOT NULL,
  `semestre` SMALLINT(1) NOT NULL,
  `cod_disc` BIGINT(0) NOT NULL,
  `mat_prof` BIGINT(0) NOT NULL,
  PRIMARY KEY (`mat_alu`, `cod_curso`, `ano`, `semestre`, `cod_disc`, `mat_prof`),
  INDEX `fk_Historico_Periodo_letivo1_idx` (`ano` ASC, `semestre` ASC, `cod_disc` ASC, `mat_prof` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Alunos1`
    FOREIGN KEY (`mat_alu` , `cod_curso`)
    REFERENCES `Unigrand`.`Alunos` (`mat_alu` , `cod_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_Periodo_letivo1`
    FOREIGN KEY (`ano` , `semestre` , `cod_disc` , `mat_prof`)
    REFERENCES `Unigrand`.`Periodo_letivo` (`ano` , `semestre` , `cod_disc` , `mat_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
